package com.dw.gbcalculator;

public enum InputSymbol {
    NUM_1,NUM_2,NUM_3,NUM_4,NUM_5,NUM_6,NUM_7,NUM_8,NUM_9,NUM_0,
    DOT,CLEAR,STEP_BACK,
    OP_PRESENT,OP_DIVISION,OP_MULTIPLY,OP_MINUS,OP_PLUS,OP_EQUALS,
    UNDEFINE
}
